### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by asarkar** [faheel/awesome-99-problems#1]
Most of the links don't have all the problems solved, just some basic ones. GitHub does what you're doing already if the repo is tagged with `99-problems`. Just link to https://github.com/topics/99-problems.

**Comment by faheel** [comment]
Some external sources, like the one for Lisp, are outside GitHub. But thanks for reporting! I'll update some outdated links add a note in the README to also check out the GitHub topics link.

**Comment by asarkar** [comment]
My point is, you’ll never be able to keep the list up-to-date, or rank the different repos. Of course, if you want to still maintain a stale list, who am I to stop you? :)
